# -*- coding: utf-8 -*-
"""Twitter (X) Social Media Sentiment Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126fVWEeKDMm3qlFft6-Vnj56a267S2hk
"""

import tweepy
# Replace this with your own bearer token
BEARER_TOKEN = " "
# Authenticate using OAuth 2.0
client = tweepy.Client(bearer_token=BEARER_TOKEN)
# Define your search query
query = "AI OR artificial intelligence -is:retweet lang:en"
# Search recent tweets
tweets = client.search_recent_tweets(
    query=query,
    max_results=10, # limit 10 for demo; max = 100
    tweet_fields=["id", "text", "created_at", "author_id"])
# Print tweet details

if tweets.data:
  for tweet in tweets.data:
    print(f"Tweet ID: {tweet.id}")
    print(f"Author ID: {tweet.author_id}")
    print(f"Time: {tweet.created_at}")
    print(f"Text: {tweet.text}\n")

else:
  print("No tweets found.")

import re
import pandas as pd
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')  # ⬅️ This line downloads the stopwords set

data = {
    'tweet_id': [1948287189076631684,1948287188929536213,1948287188874952738,1948287188099039633,1948287187411493082,1948287187411464556,1948287187411493082,1948287187411464556,1948287187377918014,1948287187369201672],
    'text': [
        "You complete me. #fyp #togel #beautifulgirl #ai #viral #labubu https://t.co/0fonNLN2w2",
        "RT @saidul_dev: Meet @lovart_ai, the world's first AI design agent!",
        "Boosting my signal on @xeetdotai 📶",
        "Ibi AI or ein norrh de talk ? https://t.co/GppuOywva",
        "Just created my page in @‌campnetworkxyz's Never Ending Story using @‌StoryChain_AI Continue Milo's story for a chance to win a @CampTrailHeads WL spot! #NeverEndingStory @campnetworkxyz @KaitoAI",
        "Just created my page in @‌campnetworkxyz's Never Ending Story using @‌StoryChain_AI Continue Milo's story for a chance to win a @CampTrailHeads WL spot! #NeverEndingStory @campnetworkxyz @KaitoAI",
        "Just created my page in @‌campnetworkxyz's Never Ending Story using @‌StoryChain_AI Continue Milo's story for a chance to win a @CampTrailHeads WL spot! #NeverEndingStory @campnetworkxyz @KaitoAI",
        "Just created my page in @‌campnetworkxyz's Never Ending Story using @‌StoryChain_AI Continue Milo's story for a chance to win a @CampTrailHeads WL spot! #NeverEndingStory @campnetworkxyz @KaitoAI",
        "RT @RBReich: UnitedHealth allegedly misused AI to deny medical claims.",
        " @zarahsultana Ai is wild. What next, fake politicians, oh we have them already."]
}
# Convert to DataFrame
df = pd.DataFrame(data)
# Define stopwords
stop_words = set(stopwords.words('english'))
# Text cleaning function
def clean_tweet(text):
  text = text.lower() # lowercase
  text = re.sub(r"http\S+", "", text) # remove URLs
  text = re.sub(r"@\w+", "", text) # remove mentions
  text = re.sub(r"#\w+", "", text) # remove hashtags
  text = re.sub(r"[^\w\s]", "", text) # remove punctuation/emojis
  text = re.sub(r"\d+", "", text) # remove digits
  words = text.split() # tokenize
  words = [word for word in words if word not in stop_words] # remove stopwords
  return " ".join(words)
# Apply cleaning to all tweets
df['clean_text'] = df['text'].apply(clean_tweet)
# Show cleaned tweets
print(df[['tweet_id', 'clean_text']])

import nltk
nltk.download('punkt')
nltk.download('stopwords')

import pandas as pd
from nltk.corpus import stopwords
from textblob import TextBlob
from collections import Counter
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import re

# Sample tweet data
data = {
    'tweet_id': [
        1948287189076631684,1948287188929536213,1948287188874952738,1948287188099039633,
        1948287187411493082,1948287187411464556,1948287187411493082,1948287187411464556,
        1948287187377918014,1948287187369201672
    ],
    'text': ["complete",
        "rt meet worlds first ai design agent",
        "boosting signal",
        "ibi ai ein norrh de talk",
        "created page campnetworkxyzs never ending story",
        "created page campnetworkxyzs never ending story",
        "created page campnetworkxyzs never ending story",
        "created page campnetworkxyzs never ending story",
        "rt unitedhealth allegedly misused ai deny medical care",
        "ai wild next fake politicians oh already"
         ]
}

df = pd.DataFrame(data)
# --- Sentiment Analysis ---
def get_sentiment(text):
    analysis = TextBlob(text)
    if analysis.sentiment.polarity > 0:
        return 'positive'
    elif analysis.sentiment.polarity < 0:
        return 'negative'
    else:
        return 'neutral'

df['sentiment'] = df['text'].apply(get_sentiment)

# --- Word Frequency ---
all_words = ' '.join(df['text']).split()
filtered_words = [word for word in all_words if word not in stopwords.words('english')]
word_freq = Counter(filtered_words)

# Top 5 most common words
print("Top 5 words:", word_freq.most_common(5))

# --- Visualization: Word Cloud ---
wordcloud = WordCloud(width=600, height=400, background_color='white').generate(' '.join(filtered_words))
plt.figure(figsize=(8, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Word Cloud of Tweets")
plt.show()

# --- Visualization: Sentiment Distribution ---
plt.figure(figsize=(6, 4))
df['sentiment'].value_counts().plot(kind='bar', color=['green', 'red', 'gray'])
plt.title("Sentiment Analysis")
plt.xlabel("Sentiment")
plt.ylabel("Tweet Count")
plt.show()

import pandas as pd
from textblob import TextBlob

# Sample tweet data (already cleaned)
data = {
    'tweet_id': [
        1948287189076631684,1948287188929536213,1948287188874952738,1948287188099039633,
        1948287187411493082,1948287187411464556,1948287187411493082,1948287187411464556,
        1948287187377918014,1948287187369201672
    ],
    'text': [
        "complete",
        "rt meet worlds first ai design agent",
        "boosting signal",
        "ibi ai ein norrh de talk",
        "created page campnetworkxyzs never ending story",
        "created page campnetworkxyzs never ending story",
        "created page campnetworkxyzs never ending story",
        "created page campnetworkxyzs never ending story",
        "rt unitedhealth allegedly misused ai deny medical care",
        "ai wild next fake politicians oh already"
    ]
}

# Load into DataFrame
df = pd.DataFrame(data)

# Sentiment analysis function
def analyze_sentiment(text):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    if polarity > 0:
        return 'positive'
    elif polarity < 0:
        return 'negative'
    else:
        return 'neutral'

# Apply sentiment analysis and polarity
df['sentiment'] = df['text'].apply(analyze_sentiment)
df['polarity'] = df['text'].apply(lambda text: TextBlob(text).sentiment.polarity)

# Display results
print(df[['tweet_id', 'text', 'sentiment', 'polarity']])

import tweepy
import networkx as nx
import matplotlib.pyplot as plt
import re

BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAJlH3AEAAAAAgfw4tG295NRPcHlavULLqlHwyyw%3DrcWzK9KXsXUk7vVob00eb92NC4qibCid1S67x3aaDBc24ja3fw"
client = tweepy.Client(bearer_token=BEARER_TOKEN)

query = "data science -is:retweet lang:en"
resp = client.search_recent_tweets(
    query=query,
    tweet_fields=["author_id", "text"],
    expansions="author_id",
    user_fields=["username"],
    max_results=20
)

# Map user ID to username
users = {str(u.id): u.username.lower() for u in resp.includes['users']}

# Create edges: who mentioned whom
edges = []
for tweet in resp.data or []:
    author = users.get(str(tweet.author_id), str(tweet.author_id))
    mentions = re.findall(r"@(\w+)", tweet.text)
    edges += [(author, m.lower()) for m in mentions]

# Build and draw the graph
G = nx.DiGraph()
G.add_edges_from(edges)
nx.draw(G, with_labels=True, node_color='skyblue', node_size=1000, font_size=10, arrowsize=15)
plt.title("Mention Network")
plt.show()